### ISSUE TITLE
Get a blurry result if I keep the same inference resolution as the original image (means scale = 1.0).

### ISSUE THREAD

**Issue by guyleaf** [compphoto/IntrinsicCompositing#6]
Hi, thank you for making this great work!

If I keep the same inference resolution as the original image (means scale = 1.0), I will have a chance to get a blurry result.
If I set the inference resolution to 1024, the result is still a little blurry.

I think it is because the harmonization model for albedo works on 384 x 384 resolution.
Do you know how to solve it?

## Result (original resolution, 1145 x 707)
![result](https://github.com/user-attachments/assets/76ea8e9b-20ea-471e-8244-ba0126200e52)
![result_intermediate](https://github.com/user-attachments/assets/cee42d02-c87f-436d-90fe-d9c7d6e1ae7c)

## Result (1024)
![result_1024](https://github.com/user-attachments/assets/35207bee-360a-4b4b-9858-2b1b9680b2f4)
![result_1024_intermediate](https://github.com/user-attachments/assets/fde6218e-b40a-4d27-ba83-fac83a6390ef)

## Composite
![composite](https://github.com/user-attachments/assets/6f1f72e9-16d5-469d-ac08-b0ed31847e16)
## Background
![bg](https://github.com/user-attachments/assets/7c5615ae-430d-43b7-82cc-4211afe41f39)
## Mask
![mask](https://github.com/user-attachments/assets/2100de1a-4953-4a9f-b442-916684824b2d)

**Comment by CCareaga** [comment]
The blurriness probably comes from the reshading estimation. The albedo harmonization is parametric so it can be applied at any resolution. The reshading network is trained at (384 x 384) but the network will make blurrier predictions at low-resolutions. I think you will find that sending the image through as large as possible will give the sharpest results, but eventually the network could exhibit some global inconsistencies due to the fixed capacity/receptive field. Another trick that can help is to upscale the image, send it through the pipeline, and then downscale the output back to the original size. This can give a sharper result than sending the image through at it's original resolution but it could degrade performance as I said before.

**Comment by guyleaf** [comment]
Hi, thanks for your response.

Oh, I see.
So, the actual problem may come from the re-shading network.

But you say sending the image through as large as possible will give the sharpest results.
In this case, the down-scaled version (1024) is less blurry than the original one, especially for the yellow object.

Sorry, I forgot to mention that the original resolution is 1145 x 707.

**Comment by CCareaga** [comment]
Yeah the estimations definitely look different on the yellow object, but when looking at the shading it's hard to tell which is blurrier. You could try sending the image through at a large resolution (e.g. 1500 or the max your GPU allows) then downscaling the shading back to the original image resolution before multiplying by the albedo. In general, this is a limitation of the model and it's difficult to get a very sharp shading layer partially due to the fact that the input normals aren't always super sharp.
